### ISSUE TITLE
Suggested edits to spreadsheet

### ISSUE THREAD

**Issue by airandfingers** [CodeForFoco/fd-servicedirectory#48]
I noticed two things off about the current values in the [Google Sheet](https://docs.google.com/spreadsheets/d/1ZPRRR8T51Tk-Co8h_GBh3G_7P2F7ZrYxPQDSYycpCUg/edit#gid=290551894):

1. Index sheet, cells C7 and C8 say "Counselins" instead of "Counseling".
2. Index sheet columns D and E repeat "house" and "water" over and over. I'd suggest changing:
  a. the "Mental Health/Addiction" rows (7 and 8) to "conversation" (and maybe "fire")
  b. the "Medical" rows (9, 10, 11) to "medical" and "fire".

**Comment by Alex-Cannon** [comment]
@airandfingers thanks for pointing this out. I'm going to close this issue as it has to do with the spreadsheet, not our codebase.

Leave this message in `p-fd-servicedirectory` and mention @michaelDurkin for a fix. Michael is our point of contact for the fire department.

Keep in mind that they should now have their own google sheet for production. The one we reference is for development only.
